version: "3.9"

services:
  db:
    image: postgres
    container_name: talent_local_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_NAME=api
      - POSTGRES_USER=talent
      - POSTGRES_PASSWORD=12345
  web:
    build: .
    container_name: talent_local_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    depends_on:
      - db
    expose:
      - 8000
    env_file: ./.env
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web


volumes:
  postgres_data: